arch_root: /mnt

# These are aliases that define file names with group vars for a host.
# The name is obtained from `ansible_product_name` fact and matched to
# corresponding file in `host_vars`.
machine_aliases:
  VirtualBox: vbox.yml
  Gazelle Professional: gzp.yml
  XPS 13 9350: xps.yml

country: United States
locales:
  - en_US
  - uk_UA

user:
  name: zoresvit
  group: zoresvit
  uid: 1000
  comment: Ruslan Kiyanchuk
  groups:
    - sys
    - video
    - wheel
    - systemd-journal
  shell: /bin/bash
  email: ruslan.kiyanchuk@gmail.com

extra_packages:
  - gvim
  - thunar
  - thunar-archive-plugin
  - keepassxc
  - git

  # Media
  - vlc
  - goldendict
  - chromium

  # Console
  - rxvt-unicode
  - bash-completion
  - mlocate

  # Filesystems
  - dosfstools
  - ntfs-3g
  - exfat-utils

  # Archives
  - zip
  - unzip
  - p7zip
  - unrar

extra_aur_packages:
  - dropbox
  - albert
  - thunar-dropbox
  - ttf-material-design-icons-git
  - kalu

dotfiles:
  repo: "https://github.com/zoresvit/dotfiles"
  install_cmd: "stow -d ${HOME}/dotfiles -S bash conky git goldendict gtk mime python tmux urxvt vim xmonad xorg"
  deps:
    - conky
    - stow
