---
- name: install bluetooth packages
  pacman:
    name:
      - blueman
      - bluez
      - bluez-libs
      - bluez-utils
      - pulseaudio-bluetooth
  notify:
    - enable bluetooth
    - restart pulseaudio as user

- name: install polkit policy for blueman
  copy:
    src: polkit/90-blueman.rules
    dest: /etc/polkit-1/rules.d/90-blueman.rules

- name: add user to lp group
  user:
    name: "{{ user.name }}"
    groups: lp
    append: yes
