---

- import_tasks: sway.yml
- import_tasks: themes.yml
- import_tasks: media.yml
- import_tasks: bluetooth.yml
- import_tasks: ssh.yml
- import_tasks: printing.yml
- import_tasks: yubikey.yml

- name: install cron
  pacman:
    name: cronie
  notify:
    - enable cron

- name: configure systemd logind.conf
  copy:
    src: logind.conf
    dest: /etc/systemd/logind.conf

- name: install MIME application associations
  copy:
    src: mimeapps.list
    dest: "/home/{{ user.name }}/.config"
    owner: "{{ user.name }}"

- import_tasks: extra_packages.yml
