---
- name: install SSH related packages
  pacman:
    update_cache: 'yes'
    name:
      - openssh
      - keychain

- name: stop SSH daemon if already running
  service:
    name: sshd
    state: stopped
  ignore_errors: 'yes'

- name: configure SSH daemon
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
  notify:
    - enable sshd

- name: create SSH dir
  file:
    path: "/home/{{ user.name }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: create SSH config
  file:
    path: "/home/{{ user.name }}/.ssh/config"
    state: touch
    mode: 0600
    owner: "{{ user.name }}"
    group: "{{ user.name }}"

- name: install ssh-agent.service
  copy:
    src: ssh-agent.service
    dest: /etc/systemd/user/ssh-agent.service
  notify:
    - enable ssh-agent

# Run handlers
- meta: flush_handlers
