---
- name: configure initramfs build hooks
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: HOOKS="{{ initramfs_hooks | join(' ') }}"

- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: restrict access permissions to initramfs
  file:
    path: "/boot/{{ item }}"
    mode: 0600
  with_items:
    - initramfs-linux.img
    - initramfs-linux-fallback.img

- name: install intel microcode
  pacman:
    name: intel-ucode
    extra_args: "--overwrite /boot/intel-ucode.img"
  when: "'GenuineIntel' in ansible_processor"

- name: install bootloader
  command: "bootctl install"

- name: retrieve UUIDs of encrypted partitions
  command: blkid -s UUID -o value /dev/disk/by-partlabel/{{ drive.partitions.0.name }}
  register: root_uuid

- name: create systemd-boot entry
  template:
    src: boot-entry.j2
    dest: /boot/loader/entries/arch.conf

- name: configure systemd-boot
  copy:
    src: loader.conf
    dest: /boot/loader/loader.conf

# TODO: not sure if still needed
- name: write EFI entry for VirtualBox
  lineinfile:
    path: /boot/efi/startup.nsh
    line: 'EFI\arch\grubx64.efi'
    create: yes
  when: ansible_product_name == "VirtualBox"
