---
- name: install sudo
  pacman:
    name: sudo
    state: present

- name: create user group
  group:
    name: "{{ user.group }}"
    state: present

- name: create user
  user:
    name: "{{ user.name }}"
    group: "{{ user.group }}"
    append: yes
    groups: "{{ user.groups | join(',') }}"
    comment: "{{ user.comment }}"
    password: "{{ hostvars.localhost.user_password }}"
    update_password: on_create

- name: set user shell
  command: chsh -s {{ user.shell }}  {{ user.name }}

- name: lock root account
  command: passwd -l root
