hostname: vbox

host_extra_packages:
  - nvidia-340xx-utils
  - virtualbox-guest-modules-arch
  - virtualbox-guest-utils

# UEFI/GPT
#disk:
#  device: /dev/sda
#  table: gpt
#  partitions:
#
#    - name: boot
#      start: 1MiB
#      end: 256MiB
#      type: primary
#      fstype: ext4
#      mountpoint: /boot
#
#    # EFI partition has to be named 'efi'!
#    - name: efi
#      start: 256MiB
#      end: 512MiB
#      type: EPS
#      fstype: vfat
#      mountpoint: /boot/efi
#
#    - name: lvm
#      start: 512MiB
#      end: 100%
#      type: primary
#      lvm_group: arch

# BIOS/GPT
disk:
  device: /dev/sda
  table: gpt
  partitions:

    - name: bios_grub
      start: 1MiB
      end: 3MiB
      type: primary
      flags: bios_grub

    - name: boot
      start: 3MiB
      end: 512MiB
      type: primary
      fstype: ext4
      mountpoint: /boot

    - name: lvm
      start: 512MiB
      end: 100%
      type: primary
      lvm_group: arch

encrypt_partition: "{{ disk.partitions[2].name }}"

lvm:
  group: arch
  volumes:

    - name: root
      size: 10G
      fstype: ext4
      mountpoint: /

    - name: var
      size: 1G
      fstype: ext4
      mountpoint: /var

    - name: swap
      size: 1G
      fstype: linux-swap

    - name: home
      size: 100%FREE
      fstype: ext4
      mountpoint: /home

